// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUgtSzgW3-hB9GcLC9mX3gs9WWzhsP-dQ',
    appId: '1:390762384296:web:9e7c4a26800f2decb36b9d',
    messagingSenderId: '390762384296',
    projectId: 'flutter-pizz',
    authDomain: 'flutter-pizz.firebaseapp.com',
    storageBucket: 'flutter-pizz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJYntYt01YtXAvbjdS_N4kHrX-PZPV390',
    appId: '1:390762384296:android:105db4d2ed9e118bb36b9d',
    messagingSenderId: '390762384296',
    projectId: 'flutter-pizz',
    storageBucket: 'flutter-pizz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCsMG1uE5Rf4TP-saAC_QmjldyTBzsIzI',
    appId: '1:390762384296:ios:f09ca4ad95620e20b36b9d',
    messagingSenderId: '390762384296',
    projectId: 'flutter-pizz',
    storageBucket: 'flutter-pizz.appspot.com',
    iosBundleId: 'com.example.flutterPizzaRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCsMG1uE5Rf4TP-saAC_QmjldyTBzsIzI',
    appId: '1:390762384296:ios:f09ca4ad95620e20b36b9d',
    messagingSenderId: '390762384296',
    projectId: 'flutter-pizz',
    storageBucket: 'flutter-pizz.appspot.com',
    iosBundleId: 'com.example.flutterPizzaRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUgtSzgW3-hB9GcLC9mX3gs9WWzhsP-dQ',
    appId: '1:390762384296:web:6e3bda9a0feecba2b36b9d',
    messagingSenderId: '390762384296',
    projectId: 'flutter-pizz',
    authDomain: 'flutter-pizz.firebaseapp.com',
    storageBucket: 'flutter-pizz.appspot.com',
  );
}
